### ISSUE TITLE
[FR] 希望能识别个人主页短链

### ISSUE THREAD

**Issue by Kauid323** [bggRGjQaUbCoE/PiliPlus#71]
### 功能描述
希望点开个人主页短链会直接跳到应用的个人主页而不是网页版的个人主页

**Comment by Kauid323** [comment]
![IMG_20241229_095104.jpg](https://github.com/user-attachments/assets/5ace76b1-ec6c-4ac4-87bf-8fe81a0152cd)

![IMG_20241229_095126.jpg](https://github.com/user-attachments/assets/ce334cf1-49b3-42a8-a868-71dde96b28c3)

**Comment by bggRGjQaUbCoE** [comment]
已优化
