### ISSUE TITLE
[FR] 增加豎屏動態比例縮放

### ISSUE THREAD

**Issue by NeKoOuO** [bggRGjQaUbCoE/PiliPlus#75]
### 功能描述
像這樣能夠自由拖動大小，目前只能夠選擇全屏跟一個半全屏，導致要看留言區也不方便，要完整看也不方便

https://github.com/user-attachments/assets/17559594-da3e-4c49-af24-0e740f1b0c22

**Comment by bggRGjQaUbCoE** [comment]
这个需要复杂的手势处理，原版加了，效果一般不说，还附带很多bug

**Comment by bggRGjQaUbCoE** [comment]
#328

**Comment by NeKoOuO** [comment]
神
